"use client";
import { useState } from "react";
import { ShieldCheck, FileCheck2, ScanLine, Globe2, Check, LockKeyhole, FileText, ChevronRight } from "lucide-react";
import AssessmentWorkflow from "@/components/assessment-workflow";

const countries = [{code:"SG",name:"新加坡",en:"Singapore",flag:"🇸🇬"},{code:"MY",name:"马来西亚",en:"Malaysia",flag:"🇲🇾"},{code:"TH",name:"泰国",en:"Thailand",flag:"🇹🇭"},{code:"ID",name:"印度尼西亚",en:"Indonesia",flag:"🇮🇩"}];
export default function Home(){
 const [view,setView]=useState("home");
 return <div className="site-shell"><header className="site-header"><div className="header-inner"><button className="brand" onClick={()=>setView("home")} aria-label="东合智检首页"><span className="brand-symbol"><ShieldCheck size={25}/></span><span>东合智检<small>DONGHE DATA CHECK</small></span></button><nav><button className={view==="home"?"nav-active":""} onClick={()=>setView("home")}>产品首页</button><button className={view!=="home"?"nav-active":""} onClick={()=>setView("profile")}>风险自查</button><a href="#boundary">使用说明</a></nav><span className="version-badge">MVP 体验版</span></div></header>
 {view==="home"?<main><section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span/>东盟数据合规 · 企业自查</div><h1>出海业务，<br/>先看清<span>数据风险。</span></h1><p>从业务场景出发，梳理数据采集、共享与跨境流转中的潜在风险，让每一步整改都有方向。</p><div className="hero-actions"><button className="primary-button" onClick={()=>setView("profile")}><ScanLine size={19}/>开始风险自查</button><a className="text-button" href="#flow">了解自查流程</a></div><div className="hero-meta"><span><Check size={15}/>无需注册</span><span><Check size={15}/>网页结果免费查看</span><span><Check size={15}/>支持 PDF 导出</span></div></div><div className="report-preview"><div className="preview-top"><div><FileCheck2 size={20}/><span>数据合规风险自查报告</span></div><span className="sample-label">示例</span></div><div className="preview-body"><div className="preview-kicker">THAILAND · 跨境直播</div><div className="preview-title"><h2>把风险看清楚，<br/>把行动列出来。</h2><span className="report-seal"><ShieldCheck size={27}/></span></div><div className="preview-stats"><div><strong>02</strong><span>高风险项</span></div><div><strong>01</strong><span>中风险项</span></div><div><strong>01</strong><span>待核实项</span></div></div>{[["high","数据跨境传输","核查接收方与传输安排"],["high","个人信息采集","明确收集目的与必要性"],["medium","第三方数据共享","梳理服务商的数据访问范围"]].map(([level,title,sub])=><div className="preview-risk" key={title}><i className={level}/><div><b>{title}</b><small>{sub}</small></div><ChevronRight size={17}/></div>)}<div className="preview-note"><FileText size={16}/>业务依据 · 法规来源 · 整改方向</div></div><div className="preview-foot"><span>示例内容仅用于展示报告形式。</span><button className="text-button" onClick={()=>setView("example")}>查看完整示例</button></div></div></section><section className="country-strip wrap"><div><Globe2 size={19}/><span>一期覆盖</span></div>{countries.map(c=><div className="country-strip-item" key={c.code}><span>{c.flag}</span><b>{c.name}</b><small>{c.en}</small></div>)}</section><section className="process-section wrap" id="flow"><div className="section-heading"><div className="eyebrow">HOW IT WORKS</div><h2>把复杂问题，分成三个清晰步骤。</h2></div><div className="process-grid">{[["01","勾选业务画像","选择目标国家、业务形态和数据回传情况。",Globe2],["02","提交业务材料","描述数据处理流程，或上传相关页面截图。",ScanLine],["03","查看风险报告","按风险等级阅读清单，获取整改方向并导出。",FileCheck2]].map(([n,t,d,Icon])=><div className="process-item" key={String(n)}><div className="process-icon">{typeof Icon!=="string"&&<Icon size={22}/>}</div><span>{String(n)}</span><h3>{String(t)}</h3><p>{String(d)}</p></div>)}</div></section></main>:<AssessmentWorkflow key={view} initialExample={view==="example"}/>}
 <section className="boundary wrap" id="boundary"><ShieldCheck size={21}/><div><b>帮助您识别风险，支持审慎决策。</b><p>本工具提供数据合规风险自查参考，不构成法律意见、合规鉴证或律师意见。涉及重要决策，请咨询专业律师。</p></div></section><footer className="site-footer wrap"><span>东合智检 <small>让出海业务的每一步更清晰</small></span><span>一期 MVP · 仅作企业自查参考</span></footer></div>;
}
