"use client";
import { useEffect, useRef, useState, type ChangeEvent, type DragEvent } from "react";
import { Globe2, LockKeyhole, UploadCloud, FileText, X, Info, ShieldCheck, Check, LoaderCircle, Download, ClipboardList, CircleHelp, RotateCcw, ScanLine } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Progress } from "@/components/ui/progress";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { COUNTRIES, BUSINESSES, TRANSFERS, LEVELS, EXAMPLE_PROFILE, EXAMPLE_DESCRIPTION, makeDemoReport, profileSchema, apiStatusSchema, apiErrorSchema, reportSchema, countryNames, businessName, reportDate, type Profile, type Report } from "@/lib/assessment";
import { exportReportPDF } from "@/lib/report-pdf";
import { aiEndpoint, canCheckApi } from "@/lib/ai-client";
type ImageItem={file:File;url:string;id:string};
type Stage="profile"|"materials"|"loading"|"report";
type MCPContext={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
export default function AssessmentWorkflow({initialExample=false}:{initialExample?:boolean}){
 const [stage,setStage]=useState<Stage>(initialExample?"report":"profile");
 const [countries,setCountries]=useState<string[]>(initialExample?[...EXAMPLE_PROFILE.country_list]:[]);
 const [business,setBusiness]=useState(initialExample?EXAMPLE_PROFILE.business_type:"");
 const [transfer,setTransfer]=useState(initialExample?EXAMPLE_PROFILE.data_transfer:"");
 const [description,setDescription]=useState(initialExample?EXAMPLE_DESCRIPTION:"");
 const [images,setImages]=useState<ImageItem[]>([]);const imagesRef=useRef<ImageItem[]>([]);
 const [report,setReport]=useState<Report|null>(initialExample?makeDemoReport():null);
 const [api,setApi]=useState<{configured:boolean;reviewed_countries:string[]}|null>(null);
 const [error,setError]=useState("");const [dragging,setDragging]=useState(false);const [progress,setProgress]=useState(8);const [exporting,setExporting]=useState(false);const [downloaded,setDownloaded]=useState(false);const [pdfLink,setPdfLink]=useState<{url:string;filename:string}|null>(null);
 const pdfRef=useRef<string|null>(null);const requestRef=useRef<AbortController|null>(null);const generation=useRef(0);const busyRef=useRef(false);
 const profile=profileSchema.safeParse({country_list:countries,business_type:business,data_transfer:transfer});const validProfile=profile.success;
 const characterCount=Array.from(description.trim()).length;const validMaterials=(characterCount===0||characterCount>=10)&&characterCount<=2000&&(characterCount>=10||images.length>0);
 const liveReady=!!api?.configured&&countries.every(c=>api.reviewed_countries.includes(c));
 useEffect(()=>{if(!canCheckApi)return;const controller=new AbortController();fetch(aiEndpoint("/api/status"),{signal:controller.signal,cache:"no-store"}).then(r=>r.ok?r.json():null).then(data=>{const parsed=apiStatusSchema.safeParse(data);if(parsed.success)setApi(parsed.data);}).catch(()=>{});return()=>controller.abort();},[]);
 useEffect(()=>{imagesRef.current=images;},[images]);
 useEffect(()=>()=>{imagesRef.current.forEach(i=>URL.revokeObjectURL(i.url));requestRef.current?.abort();if(pdfRef.current)URL.revokeObjectURL(pdfRef.current);generation.current++;},[]);
 useEffect(()=>{if(stage!=="loading")return;const timer=setInterval(()=>setProgress(p=>Math.min(92,p+Math.max(1,(94-p)*.08))),550);return()=>clearInterval(timer);},[stage]);
 const viewState=useRef({stage,countries,business,transfer,report});viewState.current={stage,countries,business,transfer,report};
 useEffect(()=>{
 const context=(document as unknown as {modelContext?:MCPContext}).modelContext;if(!context?.registerTool)return;
 const lifecycle=new AbortController();
 const tools=[{name:"get_assessment_state",title:"读取当前自查状态",description:"读取当前步骤和已选业务画像；不读取上传材料或个人信息。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("该工具不接受参数");const s=viewState.current;return {stage:s.stage,profile:{country_list:s.countries,business_type:s.business,data_transfer:s.transfer},report_mode:s.report?.mode??null};}},{name:"stage_assessment_profile",title:"填写业务画像",description:"填写国家、业务形态和数据回传情况，并停留在画像步骤；不提交材料、不调用AI。",inputSchema:{type:"object",additionalProperties:false,required:["country_list","business_type","data_transfer"],properties:{country_list:{type:"array",minItems:1,maxItems:4,uniqueItems:true,items:{type:"string",enum:["SG","MY","TH","ID"]}},business_type:{type:"string",enum:BUSINESSES.map(b=>b.value)},data_transfer:{type:"string",enum:TRANSFERS.map(t=>t.value)}}},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const p=profileSchema.parse(input);setCountries(p.country_list);setBusiness(p.business_type);setTransfer(p.data_transfer);setError("");setStage("profile");await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {stage:"profile",profile:p};}}];
 for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
 return()=>lifecycle.abort();
 },[]);
 function changeStage(next:Stage){setError("");setStage(next);window.scrollTo({top:0,behavior:"smooth"});}
 async function addImages(files:File[]){
 setError("");if(images.length+files.length>3){setError("最多上传 3 张图片，请移除部分图片后重试。");return;}
 if(files.some(f=>!(["image/jpeg","image/png"].includes(f.type)))){setError("仅支持 JPG、PNG 图片。");return;}
 if(files.some(f=>!f.size||f.size>5*1024*1024)){setError("图片不能为空，单张图片需小于或等于 5 MB。");return;}
 try{for(const f of files){const bitmap=await createImageBitmap(f);bitmap.close();}}catch{setError("图片无法读取，请重新选择有效的 JPG 或 PNG 文件。");return;}
 setImages(current=>{if(current.length+files.length>3){setError("最多上传 3 张图片。");return current;}return [...current,...files.map(file=>({file,id:crypto.randomUUID(),url:URL.createObjectURL(file)}))];});
 }
 function fileChange(event:ChangeEvent<HTMLInputElement>){void addImages(Array.from(event.target.files??[]));event.target.value="";}
 function drop(event:DragEvent<HTMLLabelElement>){event.preventDefault();setDragging(false);void addImages(Array.from(event.dataTransfer.files));}
 function removeImage(id:string){setImages(current=>{const removed=current.find(i=>i.id===id);if(removed)URL.revokeObjectURL(removed.url);return current.filter(i=>i.id!==id);});}
 async function generate(){
 if(!profile.success||!validMaterials||busyRef.current)return;
 busyRef.current=true;const run=++generation.current;const controller=new AbortController();requestRef.current=controller;setError("");setProgress(8);changeStage("loading");
 try{
 let result:Report;
 if(liveReady){const form=new FormData();form.set("profile",JSON.stringify(profile.data));form.set("description",description.trim());images.forEach(i=>form.append("images",i.file));const response=await fetch(aiEndpoint("/api/analyze"),{method:"POST",body:form,signal:controller.signal});const data=await response.json();if(!response.ok){const failure=apiErrorSchema.safeParse(data);throw new Error(failure.success?failure.data.error.message:"分析服务暂时不可用，请重试。");}const parsedReport=reportSchema.safeParse(data);if(!parsedReport.success||parsedReport.data.mode!=="live")throw new Error("分析结果不完整，请重试。");result=parsedReport.data;}
 else {await new Promise(resolve=>setTimeout(resolve,1400));result=makeDemoReport(profile.data);}
 if(run!==generation.current)return;setReport(result);setProgress(100);setDownloaded(false);setPdfLink(null);if(pdfRef.current)URL.revokeObjectURL(pdfRef.current);pdfRef.current=null;setStage("report");window.scrollTo({top:0,behavior:"smooth"});
 }catch(e){if(controller.signal.aborted||run!==generation.current)return;setError(e instanceof Error?e.message:"分析失败，请稍后重试。");setStage("materials");}finally{if(run===generation.current)busyRef.current=false;}
 }
 function cancel(){generation.current++;busyRef.current=false;requestRef.current?.abort();changeStage("materials");}
 async function download(){if(!report||exporting)return;setExporting(true);setError("");try{const file=await exportReportPDF(report);if(pdfRef.current)URL.revokeObjectURL(pdfRef.current);pdfRef.current=file.url;setPdfLink(file);setDownloaded(true);}catch{setError("PDF 生成失败，请重新尝试。");}finally{setExporting(false);}}
 function startAgain(){images.forEach(i=>URL.revokeObjectURL(i.url));setImages([]);setCountries([]);setBusiness("");setTransfer("");setDescription("");setReport(null);setDownloaded(false);setPdfLink(null);if(pdfRef.current)URL.revokeObjectURL(pdfRef.current);pdfRef.current=null;changeStage("profile");}
 const step=stage==="profile"?0:stage==="materials"||stage==="loading"?1:2;
 const ErrorMessage=error?<div className="inline-error" role="alert"><Info size={17}/>{error}</div>:null;
 if(stage==="report"&&report)return <main className="results wrap"><div className="results-heading"><div><div className="eyebrow">ASSESSMENT REPORT</div><h1>数据合规风险自查报告</h1><p>{countryNames(report.profile)} <span>·</span> {businessName(report.profile)} <span>·</span> {reportDate(report.created_at)}</p></div><div className="result-actions"><button className="secondary-button" onClick={()=>changeStage("materials")}>修改材料</button><button className="primary-button" onClick={download} disabled={exporting}>{exporting?<LoaderCircle className="spin" size={18}/>:<Download size={18}/>} {exporting?"正在生成":"免费导出 PDF"}</button></div></div>
 {report.mode==="demo"&&<div className="demo-notice" role="status"><Info size={18}/><div><b>示例报告 · 仅用于体验</b><p>以下内容基于预设演示场景，未分析您提交的文字或图片，也未核验法规，不可用作实际合规判断。</p></div></div>}
 <section className="overview"><div className="overview-intro"><span>风险总览 {report.mode==="demo"?"/ 示例":""}</span><h2>{report.risk_overview.overall_level==="unknown"?"信息仍需补充核实":"优先梳理关键风险事项"}</h2><p>先处理优先事项，再完善数据流转与日常管理。</p><span className={`overall-badge level-${report.risk_overview.overall_level}`}><ShieldCheck size={15}/>{LEVELS[report.risk_overview.overall_level].label}{report.mode==="demo"?"（示例）":""}</span></div><div className="risk-counts">{(["high","medium","low","unknown"] as const).map(l=><div key={l} className={`count-${l}`}><strong>{report.risk_overview[`${l}_count`].toString().padStart(2,"0")}</strong><span>{LEVELS[l].label}</span></div>)}</div></section>
 <div className="results-grid"><div className="risk-section"><div className="risk-section-title"><h2>风险事项清单</h2><span>共 {report.risk_list.length} 项 · 按关注优先级排列</span></div><div className="report-content"><Accordion type="multiple" defaultValue={[report.risk_list[0]?.id]}>{report.risk_list.map((r,i)=><AccordionItem key={r.id} value={r.id} className="risk-item"><AccordionTrigger className="risk-trigger"><span className="risk-index">{String(i+1).padStart(2,"0")}</span><span className="risk-trigger-text"><b>{r.title}</b><small>{r.description}</small></span><span className={`risk-badge level-${r.level}`}>{LEVELS[r.level].label}</span></AccordionTrigger><AccordionContent className="risk-detail"><div className="evidence"><FileText size={16}/><div><b>材料依据</b><p>{r.evidence}</p></div></div><div className="risk-detail-grid"><div><h3>法规来源</h3>{r.sources.length?r.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.name} · {s.article}</a><small>审核日期：{s.reviewed_at}</small></p>):<p>尚未提供经审核的法规出处，需进一步核实。</p>}</div><div><h3>可能影响</h3><p>{r.consequence}</p></div></div><div className="suggestion"><Check size={17}/><div><b>整改方向</b><p>{r.suggestion}</p></div></div></AccordionContent></AccordionItem>)}</Accordion></div></div><aside className="report-aside"><section className="report-aside-card"><span className="mini-icon"><CircleHelp size={20}/></span><h2>还需要补充什么？</h2><p>补齐信息，有助于进一步核查。</p><ul>{report.information_gaps.length?report.information_gaps.map(g=><li key={g}>{g}</li>):<li>可将报告与材料交由专业人员复核。</li>}</ul></section><section className="report-aside-card"><span className="mini-icon"><ClipboardList size={20}/></span><h2>下一步怎么做</h2><p>{report.disposal_guide}</p></section></aside></div>
 <section className="export-panel"><div className="export-icon"><FileText size={27}/></div><div><h2>把自查清单带回团队</h2><p>导出 A4 报告，便于内部讨论、存档与对照整改。{report.mode==="demo"?"示例标识将保留在报告中。":""}</p><small>PDF 保留风险明细、材料依据、来源与免责声明。</small></div><button className="primary-button" onClick={download} disabled={exporting}><Download size={18}/>{exporting?"正在生成 PDF":"免费导出 PDF"}</button></section>{downloaded&&<p className="download-success" role="status"><Check size={16}/>PDF 已生成。{pdfLink&&<a className="pdf-download-link" href={pdfLink.url} download={pdfLink.filename}>再次下载 PDF</a>}</p>}{ErrorMessage}<div className="report-bottom"><span>编号 {report.report_id} · 当前会话内有效</span><button className="text-button" onClick={startAgain}><RotateCcw size={15}/>重新开始自查</button></div></main>;
 return <main className="workspace wrap"><div className="workspace-heading"><div className="eyebrow">NEW ASSESSMENT</div><h1>开始一次风险自查</h1><p>先了解您的业务，再梳理相关的数据处理风险。</p></div><div className="workflow-grid"><aside className="workflow-aside"><h2>自查流程</h2>{["业务画像","业务材料","风险报告"].map((s,i)=><div className={`workflow-step ${i===step?"active":""} ${i<step?"complete":""}`} key={s}><span>{i<step?<Check size={16}/>:i+1}</span><div><b>{s}</b><small>{["明确范围与业务场景","提供分析所需的信息","查看风险与整改方向"][i]}</small></div></div>)}<div className="aside-note"><LockKeyhole size={20}/><h3>只提交必要的信息</h3><p>上传前请遮盖姓名、电话、账号等个人信息。结果仅作企业自查参考。</p></div>{countries.length>0&&<div className="aside-selection"><span>本次覆盖</span><div>{COUNTRIES.filter(c=>countries.includes(c.code)).map(c=><b key={c.code}>{c.name}</b>)}</div></div>}</aside><section className="form-panel">
 {stage==="profile"&&<><div className="panel-heading"><span className="step-label">STEP 01 / 03</span><h2>勾选您的业务画像</h2><p>三个问题，帮助确定自查的范围与重点。</p></div><fieldset className="question"><legend><span>01</span>业务主要覆盖哪些国家？<em>可多选</em></legend><div className="country-grid">{COUNTRIES.map(c=><label className={countries.includes(c.code)?"country-option selected":"country-option"} key={c.code}><span className="flag">{c.flag}</span><span><b>{c.name}</b><small>{c.en}</small></span><Checkbox aria-label={c.name} checked={countries.includes(c.code)} onCheckedChange={()=>setCountries(a=>a.includes(c.code)?a.filter(x=>x!==c.code):[...a,c.code])}/></label>)}</div></fieldset><fieldset className="question"><legend><span>02</span>您的核心业务形态是？<em>单选</em></legend><RadioGroup className="business-grid" value={business} onValueChange={setBusiness} aria-label="业务形态">{BUSINESSES.map(b=><label key={b.value} className={`business-option ${business===b.value?"selected":""}`}><RadioGroupItem value={b.value} id={`business-${b.value}`}/><span><b>{b.label}</b><small>{b.hint}</small></span></label>)}</RadioGroup></fieldset><fieldset className="question"><legend><span>03</span>东盟用户数据是否回传中国？<em>单选</em></legend><RadioGroup className="transfer-group" value={transfer} onValueChange={setTransfer} aria-label="数据回传情况">{TRANSFERS.map(t=><label className={`transfer-option ${transfer===t.value?"selected":""}`} key={t.value}><RadioGroupItem value={t.value} id={`transfer-${t.value}`}/><span>{t.label}</span></label>)}</RadioGroup></fieldset><div className="form-next"><span><ShieldCheck size={15}/>不需要填写企业或个人身份信息</span><button className="primary-button" disabled={!validProfile} onClick={()=>changeStage("materials")}>下一步：提交材料</button></div></>}
 {stage==="materials"&&<><div className="panel-heading"><span className="step-label">STEP 02 / 03</span><h2>提供业务材料</h2><p>文字或图片至少提供一种，描述越具体，自查越有针对性。</p></div><div className="profile-summary"><Globe2 size={16}/><span>{validProfile?countryNames(profile.data):""}</span><i/><span>{validProfile?businessName(profile.data):""}</span><button onClick={()=>changeStage("profile")}>修改画像</button></div><div className="material-section"><div className="material-label"><label htmlFor="business-description">业务场景描述</label><button className="text-button" onClick={()=>setDescription(EXAMPLE_DESCRIPTION)}>填入示例</button></div><p>可以说明：收集什么数据、用于什么业务、存在哪里、与谁共享。</p><textarea id="business-description" value={description} maxLength={4000} onChange={e=>{if(Array.from(e.target.value).length<=2000)setDescription(e.target.value);setError("");}} placeholder="例如：我们在泰国做直播带货，会收集客户手机号和收货信息，订单数据同步到国内服务器，客服与物流服务商可以访问……" rows={6}/><div className={`text-counter ${characterCount>0&&characterCount<10?"invalid":""}`}><span>{characterCount>0&&characterCount<10?"请至少填写 10 字":"选填 · 10–2000 字"}</span><span>{characterCount} / 2000</span></div></div><div className="material-section"><div className="material-label"><h3>相关页面截图</h3><span>选填 · 最多 3 张</span></div><p>如注册表单、隐私告知、数据流转说明等。</p><label className={`upload-zone ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={drop}><input type="file" accept="image/jpeg,image/png" multiple onChange={fileChange} aria-label="上传相关页面截图"/><UploadCloud size={30}/><b>点击选择图片，或拖拽到这里</b><small>JPG、PNG · 单张不超过 5 MB</small></label>{images.length>0&&<div className="image-previews">{images.map(i=><div className="image-preview" key={i.id}><img src={i.url} alt={`已选截图：${i.file.name}`}/><button onClick={()=>removeImage(i.id)} aria-label={`删除 ${i.file.name}`}><X size={15}/></button><span>{i.file.name}</span><small>{(i.file.size/1024/1024).toFixed(2)} MB</small></div>)}</div>}</div><div className="privacy-notice"><LockKeyhole size={17}/><p>请先遮盖姓名、手机号、账号等个人信息。{liveReady?"提交后，材料将发送到所配置的 AI 服务进行分析。本应用不保存上传材料或历史报告。":"示例体验不会将材料发送给 AI 服务，上传图片仅用于本地预览。"}</p></div>{!liveReady&&<div className="demo-notice compact"><Info size={17}/><div><b>当前为示例体验</b><p>真实分析暂未启用。提交后展示预设示例报告，不对您的材料作风险判断。</p></div></div>}{ErrorMessage}<div className="form-next"><button className="secondary-button" onClick={()=>changeStage("profile")}>上一步</button><button className="primary-button" onClick={generate} disabled={!validProfile||!validMaterials||busyRef.current}><ScanLine size={18}/>{liveReady?"开始 AI 自查":"生成示例报告"}</button></div></>}
 {stage==="loading"&&<div className="analysis-loading" role="status" aria-live="polite"><div className="loading-symbol"><ScanLine size={42}/><LoaderCircle size={68} className="spin"/></div><span className="eyebrow">{liveReady?"ANALYZING":"PREPARING EXAMPLE"}</span><h2>{liveReady?"正在梳理业务材料":"正在准备示例报告"}</h2><p>{liveReady?"正在结合业务画像与法规资料整理风险事项，请稍候。":"使用预设业务场景，展示完整报告结构与整改方向。"}</p><Progress value={progress} aria-label="报告生成进度"/><ul><li><Check size={15}/>明确业务范围</li><li><LoaderCircle size={15} className="spin"/>{liveReady?"梳理材料与法规依据":"整理示例风险清单"}</li><li><FileText size={15}/>生成结构化报告</li></ul><button className="text-button" onClick={cancel}>取消并返回材料</button></div>}
 </section></div></main>;
}
